# Generated by Django 2.1.5 on 2019-02-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='outline',
            new_name='description',
        ),
    ]
