# Generated by Django 2.1.5 on 2019-02-13 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('text2', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='post',
        ),
        migrations.AddField(
            model_name='postsection',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost'),
        ),
    ]
