# Generated by Django 2.1.5 on 2019-02-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190213_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/blog/photography'),
        ),
    ]
