# Generated by Django 2.1.5 on 2019-02-15 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190213_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.BlogPost'),
        ),
        migrations.AlterField(
            model_name='postsection',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blog.BlogPost'),
        ),
        migrations.AlterField(
            model_name='postsection',
            name='text2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
