# Generated by Django 2.1.5 on 2019-02-15 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
