# Generated by Django 2.1.5 on 2019-02-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='images/logos')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_group', models.CharField(max_length=50)),
                ('alt', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/gallery')),
                ('gallery_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_image', to='photography.GalleryGroup')),
            ],
        ),
    ]
