# Generated by Django 2.1.5 on 2019-04-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerygroup',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
