# Generated by Django 2.1.5 on 2019-04-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0002_gallerygroup_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerygroup',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
