# Generated by Django 2.1.5 on 2019-04-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0003_gallerygroup_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerygroup',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
