# Generated by Django 2.1.5 on 2019-04-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0004_auto_20190430_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerygroup',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
