# Generated by Django 2.1.5 on 2019-02-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0002_auto_20190211_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
