# Generated by Django 2.1.5 on 2019-02-11 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0003_auto_20190211_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_group', models.CharField(max_length=50)),
                ('alt', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('gallery_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photography.GalleryGroup')),
            ],
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
