# Generated by Django 2.1.5 on 2019-02-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0004_auto_20190211_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerygroup',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
