# Generated by Django 2.1.5 on 2019-02-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0005_gallerygroup_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerygroup',
            name='logo',
            field=models.ImageField(upload_to='images/logos'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='images/gallery'),
        ),
    ]
